version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - ./shared:/app/shared
    depends_on:
      - database
      - redis
    ports:
      - "5000:5000"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
      - ./shared:/app/shared
      - ./backend/data:/data
      - /app/venv
    depends_on:
      - database
      - redis

  database:
    image: mongo:4.4.18
    volumes:
      - ./shared:/shared
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mongo_data:

